Header
dmitrykorchagin/twitter-demo-frontend pull request #1
Opened 2018-06-15 08:59 UTC by dmitrykorchagin

Успел сделать только хедер и без активных элементов.

2018-06-15 22:52 UTC, imevro requested changes

2018-06-15 22:52 UTC, evgenyrodionov commented on src/App.js
> +import Header from "./Profile/Header/index";
1) почему хедер относится к профилю?
2) опусти index, вебпак и так сам ищет index.js при импорте

2018-06-15 22:52 UTC, evgenyrodionov commented on src/Profile/Header/index.js
> +    <div>
зачем тут это див? зачем вообще весь это компонент если можно экспортить хедер?

2018-06-15 22:52 UTC, evgenyrodionov commented on src/Profile/Header/index.js
> +import Navbar from "./profileNavbar";
зачем ты импортишь, если не используешь?

2018-06-15 22:52 UTC, evgenyrodionov commented on src/Profile/Header/index.js
> +import Header from "./topNavbar";
![image](https://user-images.githubusercontent.com/775692/41492430-c6578086-7107-11e8-8724-81e5808dd3b2.png)

2018-06-15 22:52 UTC, evgenyrodionov commented on src/Profile/Header/topNavbar.js
> +    float: left;
мы в 2018 году, это что за мусор?

2018-06-16 20:42 UTC, dmitrykorchagin commented
@evgenyrodionov  доделал страницу, вроде исправил все твои замечания, добавил NavLink, Redirect, Route 
Надеюсь этого будет достаточно, чтобы пройти в следующий этап

2018-06-18 06:05 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/41520517-bef0aebe-72d6-11e8-8832-ccc909a9cd81.png)
![image](https://user-images.githubusercontent.com/775692/41520519-c3680cda-72d6-11e8-933a-17acf6fbdbb2.png)

2018-06-18 06:09 UTC, imevro requested changes

2018-06-18 06:09 UTC, evgenyrodionov commented on src/ProfilePage/Header/ProfileNavbar.js
> +    props.activeClassName === "active" ? "#1da1f2" : "transparent"};
нет

2018-06-18 06:09 UTC, evgenyrodionov commented on src/ProfilePage/Header/ProfileNavbar.js
> +    props.activeClassName === "active" ? "#1da1f2" : "transparent"};
activeClassName указывает какой класс поставить когда будет элемент активным

2018-06-18 06:09 UTC, evgenyrodionov commented on src/ProfilePage/Header/ProfileNavbar.js
> +    props.activeClassName === "active" ? "#1da1f2" : "transparent"};
твоя проверка вообще нихуя не сработает

2018-06-18 06:09 UTC, evgenyrodionov commented on src/ProfilePage/Header/TopNavbar.js
> +  &.active {
вот тут нормально сделано

2018-06-18 06:09 UTC, evgenyrodionov commented on src/ProfilePage/Header/TopNavbar.js
> +  letter-spacing: 0.01px;
нет

2018-06-18 06:09 UTC, evgenyrodionov commented on src/ProfilePage/Header/TopNavbar.js
> +            <NavigationIcon src={notificationsIcon} />
почему иконки лежат отдельно от ссылок?

2018-06-18 06:09 UTC, evgenyrodionov commented on src/ProfilePage/Header/TopNavbar.js
> +import React from "react";
почему файл называется топнавбар?

2018-06-18 06:09 UTC, evgenyrodionov commented on src/ProfilePage/Header/TopNavbar.js
> +import searchbtn from "./img/search-button.svg";
как свг может быть кнопкой?

2018-06-18 06:09 UTC, evgenyrodionov commented on src/ProfilePage/Main/Сontent.js
> +                <NavigationList>
зачем ты вложил элемент в самого себя?

2018-06-19 10:57 UTC, imevro requested changes

2018-06-19 10:57 UTC, evgenyrodionov commented on src/ProfilePage/Main/Description.js
> +  letter-spacing: 0.01px;
нет

2018-06-19 10:57 UTC, evgenyrodionov commented on src/ProfilePage/Main/TweetNavigation.js
> +    props.activeClassName === "selected" ? "#14171a" : "#1da1f2"};
перечитай что за проп `activeClassName` в NavLink и поймешь почему некорректно так делать

2018-06-19 11:25 UTC, dmitrykorchagin commented on src/ProfilePage/Main/TweetNavigation.js
> +    props.activeClassName === "selected" ? "#14171a" : "#1da1f2"};
Не заметил, спасибо. Исправил

2018-06-20 20:52 UTC, imevro requested changes
если я комментирую только в одном месте это не означает что нужно исправить только это место, нужно пройтись по всему проекту и исправить ошибку

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/Followers/index.js
> +import avatar1 from "../img/avatar-1.jpg";
это не интерфейсные изображения, поэтому кинь в паблик

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/Followers/index.js
> +        title="6 Followers you know"
почему бы не чилдрен?

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/Followers/index.js
> +        titleLink="/EveryInteract/followers_you_follow"
если у тебя компонент называется хединг, есть ли смысл добавлять префикс title, который по сути означает тот же хединг?

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/Media/MediaPhotos.js
> +      <MediaPhotosLink exact to={photosLink}>
ты и так в файле медиафотос, зачем тебе префиксы?

плюс зачем у пропа префикс фотос?

плюс почему проп не называется просто `to`?

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/Tweets/Tweet.js
> +          <TweetAtNick>{tweetAtNick}</TweetAtNick>
ты и так в файле твит, зачем тебе префиксы твит твит твит твит

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/Tweets/Tweet.js
> +        </Action>
вынеси в отдельный компонент и передавай туда пропы, а внутри него используй икон и каунт без префиксов экшен

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/Tweets/TweetNavigation.js
> +        <NavigationLink exact to="/EveryInteract" activeClassName="active">
по дефолту и есть эктив

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/Tweets/TweetNavigation.js
>        props.activeClassName === "selected" ? "none" : "underline"};
а тут кто будет фиксить?

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/Tweets/index.js
> +        date="2 Mar 2015"
date-fns.org + передавай не отформатированные значения, форматируй уже внутри

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/WhoToFollow/Button.js
> +};
какой-то абсолютно бесполезный компонент — мало того что ты его зачем-то обернул в реакт фрагмент, так ты ещё и сделал прокладку, которая отличается от СК только тем, что ты будешь делать `<Button textButton="XXX" />` вместо `<Button>XXX</Button>` как если бы экспортнул ск

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/WhoToFollow/RecommendFollowers.js
> +const NickLink = styled.div`
как див может быть ликнмо?

2018-06-20 20:52 UTC, evgenyrodionov commented on src/ProfilePage/Main/WhoToFollow/RecommendFollowers.js
> +const AtNick = styled(NavLink)`
зачем ты используешь навлинк? ты каким-то образом будешь подчёркивать у этого элемента его активное состояние?

2018-06-22 02:36 UTC, dmitrykorchagin commented
замечания исправил, страницу доделал
по поводу чилдрена не успею обсудить до проверки

2018-06-22 20:57 UTC, imevro requested changes

2018-06-22 20:57 UTC, evgenyrodionov commented on src/ProfilePage/Main/Media/MediaPhotos.js
> +  height: 83px;
высота или ширина ставятся только изображениям

2018-06-22 20:57 UTC, evgenyrodionov commented on src/ProfilePage/Main/Trends/index.js
> +const Heading = styled.div`
а поч не h4 или что-ниб в этом духе

2018-06-22 20:57 UTC, evgenyrodionov commented on src/ProfilePage/Main/Trends/index.js
> +          description="1,036 Tweets"
почему не передаешь числом

2018-06-23 07:06 UTC, dmitrykorchagin commented on src/ProfilePage/Main/Trends/index.js
> +const Heading = styled.div`
это обертка заголовка и кнопок для того, чтобы они размещались в строку, а не колонками

2018-06-25 15:52 UTC, imevro approved these changes

2018-06-25 15:53 UTC, merged

2018-06-25 15:53 UTC, evgenyrodionov commented
Не забудь сделать гит пулл перед тем как стартовать новые ветки от мастера

Если уже делал новую ветку от этой, то коммитни изменения, сделай новую от мастера и туда черри-пиком и забери коммиты

Напиши мне в телеграм с ссылкой на этот пуллреквест, добавлю в курсач и второй этап